### ISSUE TITLE
GetAuthorizeUrl throws EpiOAuthException

### ISSUE THREAD

**Issue by nuzulul** [jmathai/twitter-async#174]
Help me !
Today suddenly all of my apps throws execption like this

Fatal error: Uncaught exception 'EpiOAuthException' in /home/a6200193/public_html/hastag/EpiOAuth.php:434 Stack trace: #0 /home/a6200193/public_html/hastag/EpiOAuth.php(404): EpiOAuthException::raise(Object(EpiCurlManager), false) #1 /home/a6200193/public_html/hastag/EpiOAuth.php(53): EpiOAuthResponse->__get('oauth_token') #2 /home/a6200193/public_html/hastag/EpiOAuth.php(60): EpiOAuth->getAuthorizeUrl(NULL) #3 /home/a6200193/public_html/hastag/user.php(41): EpiOAuth->getAuthorizationUrl() #4 {main} thrown in /home/a6200193/public_html/hastag/EpiOAuth.php on line 434

what sould i do ? 
i am frustating

**Comment by richicru** [comment]
Any solution to this problem? I'm getting the same error
